### ISSUE TITLE
Unable to run this package without Node deps such as global or EventEmitter

### ISSUE THREAD

**Issue by skalidindi** [inovua/reactdatagrid#236]
I am unable to run this project if I use Vite. 

Note, unlike Webpack, Vite does not try to shim built-in Node.js modules that may be used (for good reason tbh).

I want to try this product and move away from AG-Grid but it seems like I can not even get the basic example code to run. I get errors such as Uncaught ReferenceError: global is not defined. If I polyfill that, I get other errors such as missing EventEmitter dependency.

Edit: Here is a super simple project for [reproduction](https://github.com/skalidindi/DemoReactDataGrid). It basically tries to run the basic table from the README.

Am I doing something wrong? Because I am shocked why a browser library such this needs NodeJS modules.

**Comment by inovua-admin** [comment]
Fixed in `v4.8.6`

**Comment by robozb** [comment]
It isn't fixed well :( It reappears in version 5.2.3 in Vite.
