### ISSUE TITLE
Issue with multiselect

### ISSUE THREAD

**Issue by marcselman** [inovua/reactdatagrid#251]
When holding control or shift to multiselect rows sometimes the row(s) will not be selected.
This happens because if the mouse moves just 1 pixel when clicking it is registered as a drag I guess and the row(s) won't be selected.
In other tools (Outlook, Explorer, etc.) the selection either already happens on mousedown (instead of mouseup or click) or a drag will only be registered after a minimum number of pixels moved.

My mouse is very sensitive and when I'm working quickly to select some rows it happens often that the rows are not getting selected because of this.

It would be great if the selection could happen immediately on mousedown.

**Comment by inovua-admin** [comment]
Fixed in `v4.16.3`

**Comment by marcselman** [comment]
@inovua-admin Hm, I've been testing with the enterprise package 4.16.3 now but the issue remains. If you want I can show you using screensharing for example?

**Comment by inovua-admin** [comment]
Fixed in version `5.2.4`.
